### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by p4c0ga** [stryses/Mi-Laptop-Air12.5-8100Y-Hackintosh#2]
Hi,
When I resume the computer, after a hibernation, the trackpad does not work.
Anyone have solution?

**Comment by 846333795** [comment]
yeah！I face the same problem. Well what's more,there is some problem in  brightness control. I can't do it.
But I also want to express my gratitude for your efi file.

**Comment by stryses** [comment]
Sorry, I haven't used this computer for a long time because of my work.
Last year's release lacked the necessary files, so it didn't work.
