### ISSUE TITLE
无法使用触控板，无法调亮度，无法使用wifi，使用旧版0.6.8运作正常。

### ISSUE THREAD

**Issue by sukidesuka** [stryses/Mi-Laptop-Air12.5-8100Y-Hackintosh#3]
经过检查发现最新的0.6.9版缺少AHCI文件夹，DSDT编译的东西全没了。0.6.8版本运作正常。

**Comment by luhua98989898** [comment]
> 经过检查发现最新的0.6.9版缺少AHCI文件夹，DSDT编译的东西全没了。0.6.8版本运作正常。

为啥我放进去 进优盘启动，引导界面没安装盘呢？安装的是11.6

**Comment by luhua98989898** [comment]
> 经过检查发现最新的0.6.9版缺少AHCI文件夹，DSDT编译的东西全没了。0.6.8版本运作正常。

为啥我用0.6.8安装11.6，引导界面没安装选项

**Comment by stryses** [comment]
感谢反馈，会重新上传，工作原因很久没用这台笔记本了
